"""empty message

Revision ID: e23cec620241
Revises: 01d77f919af1
Create Date: 2019-11-30 20:49:56.207326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e23cec620241'
down_revision = '01d77f919af1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Absences',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['Classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['Students.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'class_id', 'date')
    )
    op.drop_table('Attendance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Attendance',
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('class_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['Classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['Students.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'class_id', 'date')
    )
    op.drop_table('Absences')
    # ### end Alembic commands ###
